Update main info
kicumkicum/teacher-army pull request #4
Opened 2021-06-12 14:40 UTC by kicumkicum

2021-06-12 14:41 UTC, kicumkicum commented on README.md
> +...
@zeckson Накинешь немного текста про себя?

2021-06-12 14:59 UTC, zeckson requested changes
Немножко замечаний и предложений.

И песню можно удалить я думаю, это было просто по фану

2021-06-12 14:59 UTC, zeckson commented on README.md
> +Наставника сложно найти, легко потерять и невозможно забыть. Если последний пункт нас устраивает, то первые два определенно нет. Мы - сообщество опытных разработчиков, которые хотят поделиться своим
...как обучать программирования -> как обучать программированию

2021-06-12 14:59 UTC, zeckson commented on README.md
> +Этот текст не про очередные онлайн-курсы. Этот текст про диалог один на один, между программистом и наставником, который поможет тебе составить индивидуальный план профессионального развития. Поможет
... проблемы в знаниях -> пробелы в знаниях

2021-06-12 14:59 UTC, zeckson commented on README.md
> +Если ты пришел в разработку из другой профессии, то мы поможем переиспользовать прошлый опыт, чтобы он не пропал даром. Я знаю на сколько это важно, потому что сам проходил через это.
...на сколько -> насколько

И тут предложение с Я

2021-06-12 14:59 UTC, zeckson commented on README.md
> +Мы готовы поделиться с тобой опытом и прокачать тебя, быть твоим тренером по программированию. Напиши, чтобы узнать подробности и мы созвонимся по видеосвязи на 30-40 минут. За это время мы познакоми
Напиши нам, чтобы обговорить подробности и записаться на бесплатное ознакомительное занятие?

Мне не понравилось напиши и мы созвонимся, непонятно кто мы

2021-06-12 14:59 UTC, zeckson commented on README.md
> +...
Хорошо

2021-06-12 15:03 UTC, kicumkicum commented on README.md
> +Наставника сложно найти, легко потерять и невозможно забыть. Если последний пункт нас устраивает, то первые два определенно нет. Мы - сообщество опытных разработчиков, которые хотят поделиться своим
```suggestion
Наставника сложно найти, легко потерять и невозможно забыть. Если последний пункт нас устраивает, то первые два определенно нет. Мы - сообщество опытных разработчиков, которые хотят поделиться своим опытом с новичками. Мы знаем, как не прост путь программиста и хотим сделать его проще. Мы знаем, как обучать программированию, потому что делали курсы в [@htmlacademy](https://htmlacademy.ru). И мы понимаем, что после прохождения курсов юнцы остаются наедине с собой, новыми сложностями и синдромом самозванца.
```

2021-06-12 15:04 UTC, kicumkicum commented on README.md
> +Этот текст не про очередные онлайн-курсы. Этот текст про диалог один на один, между программистом и наставником, который поможет тебе составить индивидуальный план профессионального развития. Поможет
```suggestion
Этот текст не про очередные онлайн-курсы. Этот текст про диалог один на один, между программистом и наставником, который поможет тебе составить индивидуальный план профессионального развития. Поможет определиться с выбором технологий для изучения. Поможет определить пробелы в знаниях. И поможет понять чего ты стоишь, сколько должны тебе платить.
```

2021-06-12 15:07 UTC, kicumkicum commented on README.md
> +Если ты пришел в разработку из другой профессии, то мы поможем переиспользовать прошлый опыт, чтобы он не пропал даром. Я знаю на сколько это важно, потому что сам проходил через это.
```suggestion
Если ты пришел в разработку из другой профессии, то мы поможем переиспользовать прошлый опыт, чтобы он не пропал даром. Мы знаем насколько это важно. Потому что обучение разработки это не начинания с чистого листа. Это продолжение твоего развития как личности.
```

2021-06-12 15:08 UTC, kicumkicum commented on README.md
> +Мы готовы поделиться с тобой опытом и прокачать тебя, быть твоим тренером по программированию. Напиши, чтобы узнать подробности и мы созвонимся по видеосвязи на 30-40 минут. За это время мы познакоми
```suggestion
Мы готовы поделиться с тобой опытом и прокачать тебя, быть твоим тренером по программированию. Напиши нам, чтобы обговорить подробности и записаться на бесплатное ознакомительное занятие.
```

2021-06-12 15:10 UTC, kicumkicum commented on README.md
> +Мы готовы поделиться с тобой опытом и прокачать тебя, быть твоим тренером по программированию. Напиши, чтобы узнать подробности и мы созвонимся по видеосвязи на 30-40 минут. За это время мы познакоми
Сделал отдельным саджестом. Сюда он не подсосался

2021-06-12 15:12 UTC, kicumkicum commented
Ништяк!

Песню удалил, но в целом она мне нравится)) Может ее убрать в подвал?

2021-06-12 15:23 UTC, kicumkicum commented
Не, наверно не нужна песня)

2021-06-13 14:57 UTC, zeckson reviewed
Пара соображений

2021-06-13 14:57 UTC, zeckson commented on README.md
> +- Mail: kicumkicum@gmail.com
давай тут поставим мыло на @teacher.army?

2021-06-13 14:57 UTC, zeckson commented on README.md
> +- Tg: https://t.me/kicumkicum
Может запилить бота и на него дать ссыль? Или создать отдельный аккаунт, например.

2021-06-13 15:13 UTC, kicumkicum commented on README.md
> +- Mail: kicumkicum@gmail.com
А ты сможешь это сделать?

2021-06-13 15:17 UTC, kicumkicum commented on README.md
> +- Mail: kicumkicum@gmail.com
Только я не уверен, нужно ли это на текущем этапе

2021-06-13 15:18 UTC, zeckson commented on README.md
> +- Mail: kicumkicum@gmail.com
Конечно! Надо только выбрать мыло, предлагаю `support@teacher.army`

2021-06-13 15:19 UTC, kicumkicum commented on README.md
> +- Tg: https://t.me/kicumkicum
Есть предположение, построенное на словах из интернета, что ботам пишут реже. И на общие аккаунты тоже. Потому что образуется налет официальности. А когда у тебя есть личный контакт, то как будто бы там обычный человек и ты ему просто берешь и пишешь

2021-06-13 15:20 UTC, zeckson commented on README.md
> +- Mail: kicumkicum@gmail.com
Поставил редирект к тебе kicumkicum@teacher.army

2021-06-13 15:21 UTC, kicumkicum commented on README.md
> +- Tg: https://t.me/kicumkicum
Если хочешь, то можно указать ещё и твои контакты. Я сначала хотел, но потом передумал. Потому что это часть маркетинга и она на мне. И по другой причине. Чтобы чувак не имел выбора, использовал меня как точку входа, но переправил бы я его все равно тебе

2021-06-13 15:22 UTC, zeckson commented on README.md
> +- Tg: https://t.me/kicumkicum
ok, оставляем как есть

2021-06-13 15:22 UTC, zeckson commented on README.md
> +- Mail: kicumkicum@gmail.com
Добавил тебе полные права на домен

2021-06-13 15:23 UTC, zeckson commented on README.md
> +- Tg: https://t.me/kicumkicum
Я просто думал, вдруг тебе нужна помощь это разгребать

2021-06-13 15:24 UTC, zeckson commented on README.md
> +- Tg: https://t.me/kicumkicum
Но видимо пока рано об этом думать 😆

2021-06-13 15:25 UTC, zeckson commented on README.md
> +- Tg: https://t.me/kicumkicum
> Есть предположение, построенное на словах из интернета, что ботам пишут реже. И на общие аккаунты тоже. Потому что образуется налет официальности. А когда у тебя есть личный контакт, то как будто бы там обычный человек и ты ему просто берешь и пишешь

Как маркетолог заговорил =)

2021-06-13 15:26 UTC, kicumkicum commented on README.md
> +- Mail: kicumkicum@gmail.com
Спасибо!

2021-06-13 16:16 UTC, kicumkicum reviewed
Апрув

2021-06-13 16:16 UTC, kicumkicum commented on README.md
> +Фуллстек инженер-разработчик, с опытом работы в разных сферах программирования от встроенных и мобильных приложений до масшатабируемых клиент-серверных приложений. Я разрабатывал клиент-серверные при
Текст пиздат 👍

2021-06-13 16:22 UTC, kicumkicum commented on README.md
> +Фуллстек инженер-разработчик, с опытом работы в разных сферах программирования от встроенных и мобильных приложений до масшатабируемых клиент-серверных приложений. Я разрабатывал клиент-серверные при
Но кажется, что слишком много слов приложения в первой части

2021-06-13 17:22 UTC, zeckson commented on README.md
> +Фуллстек инженер-разработчик, с опытом работы в разных сферах программирования от встроенных и мобильных приложений до масшатабируемых клиент-серверных приложений. Я разрабатывал клиент-серверные при
```suggestion
Фуллстек инженер-разработчик, с опытом работы в разных сферах программирования от встроенных и мобильных до масштабируемых клиент-серверных приложений. Я разрабатывал клиент-серверные приложения в [@jetbrains](https://jetbrains.com) и [@swiftinvention](https://www.swiftinvention.com) знаю особенности работы серверных приложений и распределённых платформ ([PAAS](https://en.wikipedia.org/wiki/Platform_as_a_service)). Учился и читал лекции в [СПб НИУ ИТМО](https://itmo.ru/), был автором курсов по Node.js и JavaScript в [@htmlacademy](https://htmlacademy.ru), а также вёл личные курсы по PHP.
```

2021-06-13 17:29 UTC, zeckson approved these changes

2021-06-13 17:29 UTC, zeckson commented
Можно мержить

2021-06-13 17:53 UTC, merged